### ISSUE TITLE
下载崩溃了

### ISSUE THREAD

**Issue by orangegithub1** [biezhihua/DYTT#1]
发现下载动漫，海贼王736集，选择除了第一个资源下载直接奔溃，下载其他的暂时没发现问题，迅雷加密那数组越界了
![bug](https://cloud.githubusercontent.com/assets/11531679/14804937/1b901a98-0b9a-11e6-9591-d53881a94e7b.png)

**Comment by biezhihua** [comment]
收到，这就处理一下，看看是什么引起的．

**Comment by biezhihua** [comment]
问题已经修复并且提交到Github上了
