### ISSUE TITLE
新建了一个项目，使用dytt的接口，没数据返回

### ISSUE THREAD

**Issue by AldenLei** [biezhihua/DYTT#6]
header添加了时间戳和request_key,request_key的加密数据是通过此项目的KeyUtils.getHeaderKey()方法获取,没有数据返回，如图
![image](https://user-images.githubusercontent.com/21965551/51077941-77d23780-16e8-11e9-88eb-abba37b05481.png)

**Comment by biezhihua** [comment]
这部分逻辑做了加密处理，暂不开源，抱歉。
